project:
  type: book
  output-dir: docs  

book:
  title: "CASA0023 Learning Diary"
  author: "Haoyu Jiang"
  date: "2026/2/19"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd
    - week7.qmd
    - week8.qmd
    - references.qmd

bibliography: references.bib
    

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    code-fold: true

editor: visual
